Repository warofants/wwa, pull requests merged in 2019-08, with the labels that each got.

#71 Feature/base architecture
  src/main/java/com/worldwarofants/game/ConsoleGame.java
  src/main/java/com/worldwarofants/game/Main.java
  src/main/java/com/worldwarofants/game/arch/AbstractController.java
  src/main/java/com/worldwarofants/game/arch/AbstractView.java
  src/main/java/com/worldwarofants/game/arch/IViewModel.java
  src/main/java/com/worldwarofants/game/arch/console/command/AbstractCommandHandler.java
  src/main/java/com/worldwarofants/game/arch/console/command/ICommand.java
  src/main/java/com/worldwarofants/game/arch/module/AbstractModule.java
  src/main/java/com/worldwarofants/game/arch/module/IModuleNavigator.java
  src/main/java/com/worldwarofants/game/arch/module/ModuleManager.java
  src/main/java/com/worldwarofants/game/assets/readme.txt
  src/main/java/com/worldwarofants/game/io/MainMenu.java
  src/main/java/com/worldwarofants/game/io/TextMenu.java
  src/main/java/com/worldwarofants/game/io/UserInterface.java
  src/main/java/com/worldwarofants/game/logic/Ant.java
  src/main/java/com/worldwarofants/game/logic/Entity.java
  src/main/java/com/worldwarofants/game/logic/QueenAnt.java
  src/main/java/com/worldwarofants/game/logic/Spider.java
  src/main/java/com/worldwarofants/game/logic/Wasp.java
  src/main/java/com/worldwarofants/game/logic/WorkerAnt.java
  src/main/java/com/worldwarofants/game/model/ExampleAnt.java
  src/main/java/com/worldwarofants/game/model/World.java
  src/main/java/com/worldwarofants/game/module/ModuleName.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ExampleCommandHandler.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ExampleController.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ExampleModule.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ExampleView.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ExampleViewModel.java
  src/main/java/com/worldwarofants/game/module/examplefeature/arch/ReproduceCommand.java
  src/main/java/com/worldwarofants/game/module/examplefeature/utils/ExampleUtils.java
  src/main/java/com/worldwarofants/game/service/AntsService.java
Labels: enhancement

#67 Replace Cobertura with JaCoCo
  .travis.yml
  codecov.yml
  pom.xml
Labels: enhancement

#64 Add caching configuration to Travis for faster builds
  .travis.yml
Labels: enhancement

#42 Added the codecov badge to the readme
  README.md
Labels: documentation, need code reviews

#106 Update Issue and Pull Request Templates Reference Issue #25
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
